// Full blog articles. Body blocks: p | h | list | code | quote
export const posts = [
  {
    slug: 'referral-bonus-system-organic-growth',
    title: 'How I Built a Referral Bonus System That Drives Organic Growth',
    date: '18 September 2026',
    category: 'Mobile App',
    image: '/blog/referral-bonus.jpg',
    excerpt: 'Paid ads burn cash. A well-designed referral loop compounds. Here is the exact system I shipped in a production grocery app.',
    minutes: 6,
    body: [
      { t: 'p', x: 'Every marketplace app eventually asks the same question: how do we grow without setting the ad budget on fire? In the Lotus Food Stores app I reached for the oldest growth lever in the book — referrals — but engineered it like a payments feature, because that is what it is: you are moving value between accounts.' },
      { t: 'h', x: 'The rules before the code' },
      { t: 'p', x: 'Before writing a single line I wrote the rules on paper, because referral fraud will find every ambiguity you leave:' },
      { t: 'list', x: ['Both sides earn — the referrer gets coins only after the referee completes a first paid order, never on signup.', 'One device, one reward — device fingerprints plus phone verification kill most duplicate accounts.', 'Coins expire — a 90-day expiry keeps the liability on our books bounded and creates urgency.', 'Every referral is an immutable ledger entry — never mutate balances directly.'] },
      { t: 'h', x: 'Ledger, not balances' },
      { t: 'p', x: 'The single most important decision: coin balances are derived, never stored as a raw number you increment. Every earn, spend and expiry is a row in a ledger table, and the balance is the sum. It makes audits trivial and race conditions nearly impossible when combined with database transactions:' },
      { t: 'code', lang: 'php', x: "DB::transaction(function () use ($user, $order) {\n    ReferralReward::create([\n        'referrer_id' => $user->referred_by,\n        'referee_id'  => $user->id,\n        'order_id'    => $order->id,\n        'coins'       => config('referral.reward_coins'),\n        'expires_at'  => now()->addDays(90),\n    ]);\n    // balance is always SUM(ledger) — never a cached column\n};" },
      { t: 'h', x: 'What actually moved the needle' },
      { t: 'p', x: 'Two details mattered more than the code. First, the share sheet had to be one tap from the home screen — every extra screen halved conversion. Second, we showed the referee their pending reward inside the app before they ordered ("Maya invited you — 200 coins waiting"), which lifted first-order conversion noticeably.' },
      { t: 'quote', x: 'Treat referral credit like money: ledger it, expire it, audit it. Growth features are financial features.' },
      { t: 'p', x: 'Six months in, referred users had a higher 90-day retention rate than users from paid channels — and they cost us a fraction to acquire. If you are building a consumer app, build the referral loop before you scale the ad spend.' },
    ],
  },
  {
    slug: 'coin-rewards-gamifying-grocery-orders',
    title: 'Coin Rewards & Redemption: Gamifying Repeat Grocery Orders',
    date: '02 September 2026',
    category: 'Mobile App',
    image: '/blog/coin-rewards.jpg',
    excerpt: 'Groceries are not exciting. Coins made them exciting. How we designed earn-and-burn mechanics that lifted repeat orders.',
    minutes: 5,
    body: [
      { t: 'p', x: 'Nobody opens a grocery app for fun. The purchase is habitual, price-sensitive and boring — which is exactly why a rewards layer works so well. In Lotus Food Stores we built a coin system that turned routine weekly shops into a small game, and repeat-order rates climbed.' },
      { t: 'h', x: 'Earn rules that feel generous but stay solvent' },
      { t: 'p', x: 'The economics have to work or the feature dies in a finance meeting. Our earn rules:' },
      { t: 'list', x: ['1 coin per 10 BDT spent — simple enough to explain in one line.', 'Bonus multipliers on slow days (Tuesday 2x) to smooth demand across the week.', 'Coins redeemable at 100 coins = 50 BDT off, capped at 20% of basket value.', 'Expiry at 90 days to keep breakage predictable.'] },
      { t: 'h', x: 'Redemption is a checkout problem' },
      { t: 'p', x: 'The trickiest engineering was not earning — it was redemption at checkout. Discounts interact with delivery fees, promo codes and refunds, and the order of operations changes the final number. We made redemption a pipeline step with a fixed precedence: item discounts first, then coins, then promo codes, then delivery fee logic.' },
      { t: 'code', lang: 'php', x: "$pipeline = [\n    new ApplyItemDiscounts,\n    new ApplyCoinRedemption($user), // capped at 20% of subtotal\n    new ApplyPromoCode($request->promo),\n    new ComputeDeliveryFee($address),\n];\n$total = array_reduce($pipeline, fn($carry, $step) => $step->apply($carry), $cart);" },
      { t: 'p', x: 'Refunds deserve a mention: when an order is refunded, redeemed coins go back to the ledger with their original expiry — not a fresh 90 days. Small detail, real money.' },
      { t: 'quote', x: 'Gamification is not confetti and badges. It is a second pricing system — design it with an accountant\u2019s discipline.' },
    ],
  },
  {
    slug: 'delivery-zones-location-restricted-ordering',
    title: 'Location-Restricted Ordering: Solving Delivery Zones the Right Way',
    date: '21 August 2026',
    category: 'Engineering',
    image: '/blog/delivery-zones.jpg',
    excerpt: 'Letting users order from stores that cannot deliver to them is a support-ticket factory. Here is how we killed it with geofencing.',
    minutes: 6,
    body: [
      { t: 'p', x: 'The most expensive bug in a delivery app is not a crash — it is an order a store cannot fulfil. Every one of those becomes a refund, a bad review and a support ticket. In Lotus Food Stores we made "can this store deliver to this address?" a hard gate, enforced server-side, before checkout is even possible.' },
      { t: 'h', x: 'Polygons, not radii' },
      { t: 'p', x: 'Simple radius checks ("within 5 km") fail in real cities — rivers, highways and one-way systems make circles a lie. We store each store\u2019s delivery area as a polygon in the database and use point-in-polygon queries:' },
      { t: 'code', lang: 'sql', x: "SELECT id, name FROM stores\nWHERE ST_Contains(delivery_zone, ST_GeomFromText('POINT(90.41 23.78)', 4326))\n  AND status = 'active';" },
      { t: 'p', x: 'MySQL and PostgreSQL both support this natively with spatial indexes, so the check runs in milliseconds even with thousands of zones.' },
      { t: 'h', x: 'Enforce on the server, hint on the client' },
      { t: 'p', x: 'The app greys out unreachable stores and explains why ("outside delivery area"), but the real enforcement lives in the order-creation endpoint. Client-side checks are UX; server-side checks are the business. We re-validate the zone at the moment of order placement, because users move and addresses get edited.' },
      { t: 'list', x: ['Store zones editable by ops staff on an admin map — no deploys to change coverage.', 'Zone check cached per user address for 15 minutes to keep listing pages fast.', 'Fallback: if GPS is off, fall back to the saved default address, never to "allow all".'] },
      { t: 'quote', x: 'Every order you prevent from failing is worth ten you fulfil brilliantly. Validation is a growth feature.' },
    ],
  },
  {
    slug: 'real-time-order-tracking-cart-to-doorstep',
    title: 'Real-Time Order Tracking: From Cart to Doorstep',
    date: '07 August 2026',
    category: 'Engineering',
    image: '/blog/order-tracking.jpg',
    excerpt: 'Users staring at a static "preparing" screen will uninstall your app. How we built live order tracking with WebSockets.',
    minutes: 7,
    body: [
      { t: 'p', x: 'Uncertainty is the enemy of delivery apps. The gap between "order placed" and "rider at your door" is where anxiety lives — and where live tracking earns its keep. Here is how I built real-time order tracking for a production grocery app.' },
      { t: 'h', x: 'The event model' },
      { t: 'p', x: 'Everything starts with a clean event model. An order moves through a strict state machine — placed, confirmed, preparing, picked_up, on_the_way, delivered, cancelled — and every transition broadcasts an event. No transition, no broadcast. The state machine is the single source of truth; the socket layer is just a megaphone.' },
      { t: 'code', lang: 'php', x: "// When a rider picks up the order\n$order->transitionTo(OrderStatus::PICKED_UP); // validates allowed transitions\n\nbroadcast(new OrderStatusChanged(\n    orderId: $order->id,\n    status: $order->status,\n    etaMinutes: $order->currentEta(),\n    rider: $order->rider->only('name', 'phone', 'lat', 'lng'),\n));" },
      { t: 'h', x: 'Rider location without melting the server' },
      { t: 'p', x: 'Rider GPS pings every 5 seconds per active delivery. At scale that is a firehose. We throttle: the server accepts pings but only rebroadcasts to the customer if the rider moved more than 50 metres or 15 seconds passed since the last broadcast. The map still feels live; the socket traffic drops by 70%.' },
      { t: 'h', x: 'Private channels and reconnection' },
      { t: 'p', x: 'Order updates go over authenticated private channels (one per order) so users can never snoop on someone else\u2019s delivery. And the app re-syncs full order state on every reconnect — sockets are for deltas, the REST endpoint is the truth. That one rule eliminated an entire class of "stuck on preparing" bugs.' },
      { t: 'quote', x: 'Real-time is not about speed — it is about trust. A calm, accurate tracker beats a flashy, wrong one.' },
    ],
  },
  {
    slug: 'building-payroll-engine-salary-deductions-payslips',
    title: 'Building a Payroll Engine: Salary, Deductions & Payslips',
    date: '24 July 2026',
    category: 'SaaS',
    image: '/blog/payroll-engine.jpg',
    excerpt: 'Payroll has zero tolerance for "close enough". How I designed an auditable salary computation engine in Laravel.',
    minutes: 7,
    body: [
      { t: 'p', x: 'Of everything I have built, payroll scared me the most. Get a grocery total wrong and someone loses a few taka; get payroll wrong and someone\u2019s rent is short. Building the salary engine for RyseNova taught me that payroll is not arithmetic — it is accounting, and accounting demands an audit trail.' },
      { t: 'h', x: 'Computation as a pipeline of named steps' },
      { t: 'p', x: 'Instead of one giant "calculate salary" method, every payslip is produced by an ordered pipeline of small, named, testable steps. Each step reads the running payslip, adds its line items, and records exactly what it did:' },
      { t: 'code', lang: 'php', x: "class ComputeOvertime implements PayrollStep {\n    public function apply(Payslip $slip): void {\n        $hours = $slip->employee->overtimeHoursFor($slip->period);\n        $amount = $hours * $slip->employee->overtimeRate();\n        $slip->addEarning('Overtime', $amount, [\n            'hours' => $hours,\n            'rate'  => $slip->employee->overtimeRate(),\n        ]);\n    }\n}" },
      { t: 'p', x: 'Because every line item carries its inputs, any payslip can be re-explained line by line months later. "Why is this number 4,250?" has an answer, always.' },
      { t: 'h', x: 'Idempotency is non-negotiable' },
      { t: 'p', x: 'Payroll runs get retried — networks fail, admins double-click. Every run is keyed by (company, period) with a unique constraint, and re-running a completed period returns the existing payslips instead of creating duplicates. I have seen what double payroll looks like in a staging database. Never again.' },
      { t: 'list', x: ['Draft → reviewed → locked → paid: payslips move through states, and locked payslips are immutable.', 'All money math in integers (poisha), never floats.', 'Every run stores a snapshot of the salary structure — future policy changes never rewrite history.'] },
      { t: 'quote', x: 'In payroll, the audit trail is the feature. The numbers are just the output.' },
    ],
  },
  {
    slug: 'attendance-leave-workflows-hr-teams-use',
    title: 'Attendance & Leave Workflows HR Teams Actually Use',
    date: '10 July 2026',
    category: 'SaaS',
    image: '/blog/attendance-leave.jpg',
    excerpt: 'HR software fails when it models the policy manual instead of real humans. What I learned building attendance and leave for RyseNova.',
    minutes: 5,
    body: [
      { t: 'p', x: 'Most HR software is designed for an imaginary company where everyone works 9-to-5 and never forgets to check in. Real companies have night shifts, field staff, half-days and managers who approve leave from their phones at 11pm. Building attendance and leave for RyseNova forced me to design for the messy reality.' },
      { t: 'h', x: 'Attendance: capture everything, judge later' },
      { t: 'p', x: 'The golden rule of attendance systems: never lose a punch. Check-ins are append-only events — even a "wrong" punch is data. Corrections happen as separate adjustment records with an approver attached, so the raw history is never rewritten. This one design choice ended every "the system ate my attendance" argument permanently.' },
      { t: 'h', x: 'Leave: state machines beat status columns' },
      { t: 'p', x: 'A leave request is not a row with a status — it is a workflow: drafted → submitted → manager-approved → hr-approved → availed, with cancellations and rejections branching off at defined points. Modelling it as an explicit state machine gave us two wins: the UI always knew exactly which actions were legal, and the audit log wrote itself.' },
      { t: 'list', x: ['Leave balances computed from accrual rules per policy — monthly, yearly, or custom.', 'Holiday calendars per company, because "public holiday" is not universal.', 'Manager dashboard: pending approvals surfaced in one tap, because approvals rot when buried.'] },
      { t: 'quote', x: 'Enterprise UX is measured in taps-to-done. Every approval buried three screens deep is a policy people will route around.' },
    ],
  },
];
