import { posts as part1 } from './posts-1';

const part2 = [
  {
    slug: 'restful-apis-large-scale-erp',
    title: 'Designing RESTful APIs for Large-Scale ERP Systems',
    date: '26 June 2026',
    category: 'Laravel',
    image: '/blog/restful-apis.jpg',
    excerpt: 'ERP APIs live for a decade and serve five clients at once. The design principles that kept ours stable through years of change.',
    minutes: 8,
    body: [
      { t: 'p', x: 'Consumer APIs can break things and apologise. ERP APIs cannot — they feed the mobile app, the web dashboard, the reporting service and the occasional Excel macro someone in accounting refuses to give up. Here is what years of ERP API work taught me about designing endpoints that survive.' },
      { t: 'h', x: 'Resources, not procedures' },
      { t: 'p', x: 'The temptation in ERP is RPC-style endpoints: /api/approveInvoice, /api/cancelOrderAndRefund. Resist it. Model the domain as resources with state transitions instead — POST /invoices/{id}/approvals, POST /orders/{id}/cancellation. Your API stays uniform, and every action becomes auditable by construction.' },
      { t: 'h', x: 'Version in the URL, evolve with additive changes' },
      { t: 'p', x: 'We version in the URL (/api/v1/...) and follow one rule: v1 never breaks. New fields get added, never renamed; behaviour changes ship in v2. In four years we have needed exactly two major versions — because additive evolution covered everything else.' },
      { t: 'code', lang: 'php', x: "// API Resource: the contract clients code against\nclass InvoiceResource extends JsonResource {\n    public function toArray($request): array {\n        return [\n            'id'          => $this->id,\n            'number'      => $this->invoice_number,\n            'status'      => $this->status, // draft|issued|paid|void\n            'total'       => (int) $this->total_poisha,\n            'line_items'  => InvoiceItemResource::collection($this->lineItems),\n            // added in 2024 — old clients simply ignore it\n            'due_date'    => $this->due_date?->toDateString(),\n            'links'       => [\n                'approve' => route('api.v1.invoices.approve', $this),\n            ],\n        ];\n    }\n}" },
      { t: 'h', x: 'Pagination, filtering and the N+1 tax' },
      { t: 'p', x: 'ERP list endpoints serve tables with 100k+ rows. Cursor pagination (not offset) keeps deep pages fast, sparse fieldsets (?fields=id,number,total) keep payloads small for the mobile app, and every list endpoint gets an integration test asserting the query count — the N+1 tax is real and it compounds.' },
      { t: 'list', x: ['Every response enveloped consistently: { data, meta, links }.', 'Errors use RFC 7807 problem details — clients parse them, humans read them.', 'Rate limits per API key with headers clients can respect.'] },
      { t: 'quote', x: 'An API is a promise. Design like you will have to keep it for ten years — because in ERP, you will.' },
    ],
  },
  {
    slug: 'llms-bangla-healthcare-paraphrasing',
    title: 'Comparing LLMs and Transformers for Bangla Healthcare Paraphrasing',
    date: '12 June 2026',
    category: 'AI Research',
    image: '/blog/llm-paraphrasing.jpg',
    excerpt: 'My IEEE ICCIT 2025 paper: what actually works when you ask models to paraphrase Bangla medical text — and what does not.',
    minutes: 7,
    body: [
      { t: 'p', x: 'Bangla is spoken by 230+ million people, yet in NLP it is firmly low-resource — and in healthcare communication the stakes of a bad paraphrase are real. For our IEEE ICCIT 2025 paper we asked a practical question: when you need to paraphrase Bangla healthcare text, do massive LLMs beat smaller fine-tuned transformers?' },
      { t: 'h', x: 'The setup' },
      { t: 'p', x: 'We compared instruction-tuned LLMs (prompted, few-shot) against smaller transformer models fine-tuned specifically for Bangla paraphrasing. Evaluation mixed automatic metrics (BLEU, ROUGE, BERTScore) with human judgement on three axes that matter in healthcare: meaning preservation, fluency, and — critically — factual consistency. A fluent paraphrase that changes a dosage instruction is worse than useless.' },
      { t: 'h', x: 'What we found' },
      { t: 'list', x: ['Fine-tuned smaller models were more reliable at preserving medical meaning — they hallucinated less.', 'Large LLMs produced more fluent, natural Bangla but occasionally "improved" the text by adding plausible-sounding details that were not in the source.', 'Few-shot prompting closed much of the fluency gap for LLMs but did not fix the factual-drift problem.', 'Human evaluators consistently penalised factual drift far more harshly than automatic metrics did.'] },
      { t: 'h', x: 'The takeaway for builders' },
      { t: 'p', x: 'If you are building with LLMs in a high-stakes domain in a low-resource language: do not trust fluency. Evaluate factual consistency separately, with humans, on your actual data. The prettiest output is not the safest output — and in healthcare, safe beats pretty every time.' },
      { t: 'quote', x: 'In low-resource NLP, the benchmark that matters is the one your users\u2019 safety depends on — not the leaderboard.' },
      { t: 'p', x: 'Full paper: "Comparative Study of LLMs and Transformers for Bangla Healthcare Paraphrasing", IEEE ICCIT 2025 proceedings (2026).' },
    ],
  },
  {
    slug: 'bidwesh-bangla-hate-speech-dataset',
    title: 'BIDWESH: Building a Bangla Hate-Speech Detection Dataset',
    date: '28 May 2026',
    category: 'AI Research',
    image: '/blog/bidwesh-dataset.jpg',
    excerpt: 'You cannot detect what you cannot measure. How we built one of the first labelled Bangla hate-speech datasets — arXiv:2507.16183.',
    minutes: 6,
    body: [
      { t: 'p', x: 'English has dozens of hate-speech datasets. Bangla — spoken by hundreds of millions — had almost nothing labelled and public. That gap is why we built BIDWESH, a Bangla hate-speech detection dataset, now on arXiv as a preprint. Here is what building a dataset for a low-resource language actually involves.' },
      { t: 'h', x: 'Collection: where the data lives' },
      { t: 'p', x: 'Bangla online discourse lives on Facebook and YouTube far more than on X/Twitter, so that is where we collected. The unglamorous truth of dataset work: 80% of the effort is cleaning — deduplication, normalising the chaos of Bangla-English code-mixing, and filtering out the noise without filtering out the dialects.' },
      { t: 'h', x: 'Annotation: guidelines are everything' },
      { t: 'p', x: 'Hate speech annotation is genuinely hard — annotators disagree, context matters, and sarcasm exists. We wrote detailed annotation guidelines with Bangla-specific examples (what counts as targeted abuse vs. heated disagreement), used multiple annotators per item, and measured inter-annotator agreement before trusting any label. A dataset is only as good as its guidelines.' },
      { t: 'h', x: 'Baselines: prove it is learnable' },
      { t: 'p', x: 'A dataset without baselines is a homework assignment with no answer key. We fine-tuned transformer models on BIDWESH to establish baseline performance — proving the signal is real and giving future researchers something to beat.' },
      { t: 'list', x: ['Preprint: arXiv:2507.16183', 'Covers multiple hate-speech categories with annotator agreement scores', 'Intended as an open resource for Bangla NLP researchers'] },
      { t: 'quote', x: 'Datasets are infrastructure. Unsexy, essential, and the highest-leverage thing a low-resource NLP researcher can build.' },
    ],
  },
  {
    slug: 'lessons-low-resource-nlp-bangla',
    title: 'Lessons from Low-Resource NLP: Working with Bangla',
    date: '14 May 2026',
    category: 'AI Research',
    image: '/blog/bangla-nlp.jpg',
    excerpt: 'Multilingual models promise the world for languages like Bangla. The reality is more nuanced — here is what two research projects taught me.',
    minutes: 6,
    body: [
      { t: 'p', x: 'Working on Bangla NLP — between the BIDWESH dataset and our IEEE healthcare paraphrasing paper — taught me lessons that do not appear in multilingual-model marketing. If you build for a low-resource language, these will save you months.' },
      { t: 'h', x: '1. "Multilingual" does not mean "equally good"' },
      { t: 'p', x: 'A model trained on 100 languages has seen orders of magnitude less Bangla than English. Tokenisation is often the silent killer: Bangla text gets split into far more tokens, which costs more, runs slower and degrades quality. Always check tokens-per-word for your language before choosing a model.' },
      { t: 'h', x: '2. Code-mixing is the norm, not the edge case' },
      { t: 'p', x: 'Real Bangla online text mixes Bangla script, romanised Bangla ("Banglish") and English — sometimes in one sentence. Models and datasets that assume clean monolingual input fail on real data. Your evaluation set must look like the street, not the textbook.' },
      { t: 'h', x: '3. Small fine-tuned models punch above their weight' },
      { t: 'p', x: 'Repeatedly, a smaller model fine-tuned on good Bangla data beat a giant prompted model on domain tasks. Data quality beats parameter count when the language is under-represented in pretraining. This is the most economically important lesson: you often do not need the biggest model, you need the best dataset.' },
      { t: 'h', x: '4. Human evaluation is mandatory' },
      { t: 'p', x: 'Automatic metrics correlate weakly with quality for Bangla generation tasks. Native-speaker judgement caught failures — factual drift, unnatural phrasing, cultural misses — that BLEU and ROUGE sailed past. Budget for it.' },
      { t: 'quote', x: 'Low-resource NLP is not "NLP but smaller". It is a different discipline — and data work is its superpower.' },
    ],
  },
  {
    slug: 'laravel-performance-tuning-needle',
    title: 'Performance Tuning in Laravel: What Actually Moves the Needle',
    date: '30 April 2026',
    category: 'Laravel',
    image: '/blog/laravel-performance.jpg',
    excerpt: 'Forget micro-optimisations. The five fixes that took our ERP endpoints from seconds to milliseconds.',
    minutes: 7,
    body: [
      { t: 'p', x: 'I have tuned Laravel apps serving ERP workloads with tables in the millions of rows. Here is the honest ranking of what actually moved the needle — measured, not theorised.' },
      { t: 'h', x: '1. Kill the N+1 (the usual suspect, because it is usually guilty)' },
      { t: 'p', x: 'Eager loading is step zero, but the real win is catching N+1s in CI before they ship. We assert query counts on list endpoints in tests — a regression that adds 200 queries fails the build.' },
      { t: 'code', lang: 'php', x: "// In tests: fail if the endpoint is chatty\nDB::enableQueryLog();\n$this->getJson('/api/v1/invoices');\n$this->assertLessThan(15, count(DB::getQueryLog()));" },
      { t: 'h', x: '2. Indexes for your actual queries, not your schema' },
      { t: 'p', x: 'Run EXPLAIN on your five slowest endpoints and index what they filter and sort by — composite indexes in the right column order. One composite index on (company_id, status, created_at) took an invoice listing from 2.1s to 40ms. Partial indexes (WHERE status = ...) are underused magic for hot subsets.' },
      { t: 'h', x: '3. Cache the computed, queue the heavy' },
      { t: 'p', x: 'Dashboard aggregates get cached with tagged invalidation; report generation moves to queues with a "your export is ready" notification. Users perceive a queued job with progress as fast — a 30-second synchronous request as broken.' },
      { t: 'h', x: '4. Select only what you need' },
      { t: 'p', x: 'SELECT * on a table with TEXT columns, hydrated into Eloquent models, serialized to JSON — for a mobile list screen that shows three fields. Specify columns, use API Resources as the contract, and watch payload sizes collapse.' },
      { t: 'h', x: '5. Database over code, always' },
      { t: 'p', x: 'Sums, counts and grouped aggregations belong in SQL, not in PHP loops over collections. If you are looping 50k models to compute a total, the database can do it in one indexed pass.' },
      { t: 'quote', x: 'Measure first, optimise second, and never optimise what you have not measured. The slow query log is the only honest consultant.' },
    ],
  },
  {
    slug: 'wordpress-to-fullstack-journey',
    title: 'From WordPress to Full-Stack: My Journey as a Software Engineer',
    date: '16 April 2026',
    category: 'Career',
    image: '/blog/fullstack-journey.jpg',
    excerpt: 'I started building WordPress sites. Four years later I ship ERP systems, mobile apps and publish AI research. The unglamorous middle.',
    minutes: 5,
    body: [
      { t: 'p', x: 'In 2022 I was building WordPress sites — themes, plugins, page builders. Today I build large-scale ERP systems, ship a React Native app on Google Play, and publish NLP research. Nobody hands you that trajectory; here is the unglamorous version of how it happened.' },
      { t: 'h', x: 'Phase 1: Learn how the web actually works' },
      { t: 'p', x: 'WordPress taught me the shape of the web — requests, databases, templates — but hid all the machinery. The jump to Laravel was the jump from assembling furniture to woodworking: suddenly I owned the queries, the auth, the queues. It was slower at first and ten times more educational.' },
      { t: 'h', x: 'Phase 2: Get beaten up by production' },
      { t: 'p', x: 'Nothing teaches like real users. Production taught me about N+1 queries at 2am, race conditions in payment flows, and why you never deploy on Friday. Every outage was a curriculum. I started writing the post-mortem before the fix — understanding first, patching second.' },
      { t: 'h', x: 'Phase 3: Go deep in one place, wide in others' },
      { t: 'p', x: 'I went deep on backend Laravel/MySQL — the part where money and data live — while staying dangerous in React, React Native and Vue. T-shaped: deep enough in one stack to be trusted with the hard problems, broad enough to ship whole products.' },
      { t: 'h', x: 'Phase 4: Research as a forcing function' },
      { t: 'p', x: 'The Bangla NLP research started as curiosity and became a discipline. Writing papers forced a rigour — baselines, ablations, honest evaluation — that bled back into my engineering. I now A/B my assumptions like hypotheses.' },
      { t: 'quote', x: 'Careers compound like interest: boring consistency in fundamentals, paid out over years. There is no shortcut — but there is a direction.' },
      { t: 'p', x: 'If you are starting where I started: learn the machinery, ship to production early, and let real users be your harshest — and best — teachers.' },
    ],
  },
];

export const posts = [...part1, ...part2];
export const postCategories = ['All', ...new Set(posts.map(p => p.category))];
