export const works = [
  {
    slug: 'lotus-food-stores',
    title: 'Lotus Food Stores',
    category: 'Mobile App',
    image: '/works/lotus-food-stores.png',
    tagline: 'Grocery delivery app serving Sydney — live on Google Play.',
    stack: ['React Native', 'Laravel', 'MySQL', 'WebSockets', 'Google Maps API'],
    timeline: '2023 – 2024',
    role: 'Mobile & Backend Developer',
    overview: [
      'Lotus Food Stores is a grocery delivery app built for a Sydney-based chain — customers browse stores, order groceries and track deliveries in real time. I worked across the React Native app and the Laravel backend that powers it.',
      'The hard parts were the ones users never see: location-restricted ordering so customers can only order from stores that deliver to them, a coin-rewards system that keeps people coming back, and real-time order tracking from cart to doorstep.',
    ],
    features: [
      'Store discovery with delivery-zone validation',
      'Real-time order tracking via WebSockets',
      'Coin rewards & redemption system',
      'Referral bonus engine driving organic growth',
      'Push notifications for order status changes',
    ],
    results: [
      'Live on Google Play with thousands of installs',
      'Repeat-order rate lifted by the rewards system',
      'Sub-second order status updates in production',
    ],
  },
  {
    slug: 'rysenova',
    title: 'RyseNova',
    category: 'Web App',
    image: '/works/rysenova.png',
    tagline: 'Cloud HR & payroll SaaS — rysenova.com.',
    stack: ['Laravel', 'Vue.js', 'MySQL', 'REST APIs'],
    timeline: '2023 – 2025',
    role: 'Full-Stack Developer',
    overview: [
      'RyseNova is a cloud HR and payroll SaaS platform. Companies run attendance, leave, salary computation and payslips from one dashboard — I built core backend modules and several frontend workflows.',
      'Payroll is unforgiving: every number has to be exactly right. I designed the salary engine around explicit, auditable computation steps — basic, allowances, deductions, overtime — so any payslip can be traced back to its inputs.',
    ],
    features: [
      'Payroll engine: salary structures, deductions, payslips',
      'Attendance tracking with shift & roster support',
      'Leave workflows with multi-level approvals',
      'Employee self-service portal',
      'Role-based access for HR, managers and staff',
    ],
    results: [
      'Serving real businesses with monthly payroll runs',
      'Payslip generation reduced from hours to minutes',
      'Auditable computation — every figure traceable',
    ],
  },
  {
    slug: 'erp-systems',
    title: 'ERP Systems',
    category: 'Web App',
    image: '/works/erp-systems.png',
    tagline: 'Large-scale ERP for e-commerce and hotel operations.',
    stack: ['Laravel', 'MySQL', 'Vue.js', 'REST APIs'],
    timeline: '2022 – 2025',
    role: 'Backend Developer',
    overview: [
      'I have built and extended large-scale ERP systems covering e-commerce and hotel operations — inventory, invoicing, procurement and reporting modules used daily by operations teams.',
      'ERP work taught me to design for scale from day one: partial indexes on hot tables, queued jobs for heavy reports, and API contracts that stay stable while modules evolve underneath.',
    ],
    features: [
      'Inventory & stock management with low-stock alerts',
      'Invoicing, billing and payment tracking',
      'Procurement and supplier management',
      'Role-based dashboards and reporting',
      'RESTful APIs consumed by web and mobile clients',
    ],
    results: [
      'Daily use by operations teams across businesses',
      'Report generation moved to queues — no more timeouts',
      'Stable API contracts across major module upgrades',
    ],
  },
  {
    slug: 'ayers-food',
    title: 'Ayers Food',
    category: 'Web App',
    image: '/works/ayers-food.png',
    tagline: 'Frozen & dry food brand — Sydney. ayersfood.com.',
    stack: ['Laravel', 'Vue.js', 'MySQL'],
    timeline: '2024',
    role: 'Full-Stack Developer',
    overview: [
      'Ayers Food is a frozen and dry food brand based in Sydney. I built their web presence and ordering workflows — product catalogues, bulk-order handling and a smooth mobile-first storefront.',
    ],
    features: [
      'Product catalogue with category filtering',
      'Bulk / wholesale ordering workflows',
      'Mobile-first responsive storefront',
      'Enquiry and contact pipelines',
    ],
    results: [
      'Live brand site serving Sydney customers',
      'Wholesale enquiries handled end-to-end online',
    ],
  },
  {
    slug: 'hotel-grace-cox',
    title: 'Hotel Grace Cox',
    category: 'Web App',
    image: '/works/hotel-grace-cox.png',
    tagline: 'Smart hotel in Cox\u2019s Bazar — 70 rooms. hotelgracecox.com.',
    stack: ['Laravel', 'Vue.js', 'MySQL'],
    timeline: '2024',
    role: 'Full-Stack Developer',
    overview: [
      'Hotel Grace Cox is a 70-room smart hotel in Cox\u2019s Bazar. I built the booking-facing website and the operational tooling behind it — room inventory, seasonal pricing and reservation management.',
    ],
    features: [
      'Room catalogue with live availability',
      'Seasonal pricing engine',
      'Reservation request management',
      'Gallery and amenities showcase',
    ],
    results: [
      'Direct bookings flowing through the site',
      'Front-desk workload reduced via online requests',
    ],
  },
  {
    slug: 'bidwesh-research',
    title: 'BIDWESH Research',
    category: 'AI Research',
    image: '/works/bidwesh-research.png',
    tagline: 'Bangla hate-speech detection dataset — arXiv:2507.16183.',
    stack: ['Python', 'Transformers', 'NLP', 'Data Annotation'],
    timeline: '2024 – 2025',
    role: 'Co-author & Researcher',
    overview: [
      'BIDWESH is a Bangla hate-speech detection dataset I co-authored, published as a preprint on arXiv. Low-resource languages like Bangla lack quality labelled data — this work helps close that gap.',
      'Alongside it, my IEEE ICCIT 2025 paper compared LLMs and transformers for Bangla healthcare paraphrasing — practical evaluation of what actually works for Bangla text.',
    ],
    features: [
      'Curated, labelled Bangla hate-speech dataset',
      'Annotation guidelines for low-resource settings',
      'Baseline transformer evaluations',
      'IEEE ICCIT 2025 paper on Bangla paraphrasing with LLMs',
    ],
    results: [
      'Preprint on arXiv (2507.16183)',
      'Paper accepted at IEEE ICCIT 2025',
      'Open resource for Bangla NLP researchers',
    ],
  },
];

export const workCategories = ['All', 'Mobile App', 'Web App', 'AI Research'];
